config-version = '1.1.1'
###
# [ Datapack Builder ]
# This config file describes your datapack and the releases
###
# Options:
# 	title = <title>
#   version = <version>
#   name-format = <string w/ {} denotating output naming format>
#      ex: '{title}-{version}-{release_name}'
#   output-folder = <folder name to output>

title       = 'MyProject'
version     = 'v1.0.0'
name-format = '{title} {version} {release_name}'

[global]

###
# This defines rules for all releases
# Note that all options are optional
###
# Options:
# 	ignore    = [<list of patterns>]
#  	whitelist = [<list of patterns>]
###

	ignore    = ['releases/*', 'docs/*', 'fabric.mod.json', '*.paper.*']
	whitelist = ['*.json', '*.mcfunction', '*.nbt', 'pack.png', 'pack.mcmeta']

[releases]

###
# This defines rules per release.
# Note that all options are optional.
###
# [releases.<name>]
#   name     = <override name of zipfile>
#   ending   = <alternative zip ext (.zip is default)>
# 	ignore   = [<list of patterns>]
#	replacer = {<if pat matches>: <replace contents of this file>}
#	include  = ['<list of included items'] (overrides ignore)
#   regex    = {'<regex>': <replace>}
###

	[releases.standard]
		name = ''

	[releases.fabric]
		ending  = '.jar'
		rules = [
			{ ignore  = ['pack.mcmeta']     },
			{ include = ['fabric.mod.json'] },
		]

		# or

		[[releases.fabric.rules]]
			ignore = ['pack.mcmeta']
		[[releases.fabric.rules]]
			include = ['fabric.mod.json']

	[releases.paper]
		rules = [
			{ replacer = {'.paper.mcfunction'='.mcfunction'} }
		]
